### ISSUE TITLE
Package dependencies.

### ISSUE THREAD

**Issue by jackokring** [fsspec/ossfs#76]
`ossfs 2023.1.0 has requirement fsspec==2022.11.0, but you have fsspec 2023.1.0.`

**Comment by karajan1001** [comment]
Thanks for your reporting.  Now the latest version of `ossfs` is `2023.3.0` and it depends on the `2023.3.0` version of fsspec. I'll try to keep the version of `ossfs` sync with `fsspec`.

Some related discussions. https://github.com/fsspec/filesystem_spec/discussions/1239
